version: '3.8'

services:
  jmzqc:
    build: .
    ports:
      - "38888:8888"
    # volumes:
    #   - ./jmzqc_lipidomics_demo.ipynb:/home/jovyan/work/jmzqc_lipidomics_demo.ipynb
    #   - .:/home/jovyan/work
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root